### ISSUE TITLE
Too many excludes

### ISSUE THREAD

**Issue by bobisjan** [codeclimate-community/codeclimate-watson#3]
Hi,

I've just encounter an error `/usr/src/app/bin/codeclimate-watson:19:in``': Argument list too long - ember-watson`.

With configuration like below, ember-watson gets a lot of `-e path/to/file` arguments.

``` yml

---
engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  watson:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.css"
exclude_paths:
- bin/**/*
- bower_components/**/*
- config/**/*
- dist/**/*
- node_modules/**/*
- tests/**/*
- tmp/**/*
- vendor/**/*
```

Thanks
